/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Join_tmp */

#ifndef _Included_Join_tmp
#define _Included_Join_tmp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Join_tmp
 * Method:    get_result
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;II)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Join_1tmp_get_1result
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
