/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cpu */

#ifndef _Included_Cpu
#define _Included_Cpu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Cpu
 * Method:    get_result
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;II)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Cpu_get_1result
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
